CREATE DATABASE IF NOT EXISTS minimal_rgb_slider
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_general_ci;

USE minimal_rgb_slider;

CREATE TABLE IF NOT EXISTS colors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  red TINYINT UNSIGNED NOT NULL,
  green TINYINT UNSIGNED NOT NULL,
  blue TINYINT UNSIGNED NOT NULL,
  name VARCHAR(64) NULL
);
